### ISSUE TITLE
Support Stack Sets

### ISSUE THREAD

**Issue by flomotlik** [flomotlik/formica#67]
Stack sets are a great way to manage the same resources across multiple accounts/regions. Formica should get support for them natively. They should be implemented as set of subcommands `formica stack-set XXX` separate from normal stack handling.

*  formica stack-set create

Creates a new StackSet with the template from the current folder

* formica stack-set remove

Remove the specified stack set

* formica stack-set update

Updates the template of an existing Stack-Set

Imho any action beyond that is better done through the awscli directly. Formica should really only concern itself with the template part of the stack-set, not with setting up which accounts/regions it gets deployed to unless we find a good reason for it. Imho that can be better done with pure AWSCLI as its a very simple command call and there is practically no upside to having this in Formica. AWSInfo could get a few more commands to better list stack sets, instances of the stacks and operations. I want to make sure we only implement the most necessary here. @ryansb thoughts?

**Comment by ryansb** [comment]
I don't think I've used StackSets frequently enough to have a strong opinion about it. I imagine if I have StackSet-related needs, the Change/Deploy cycle in formica would only be useful on individual stacks in the set, is that right?
