### ISSUE TITLE
Add flag for removing stack on failed create

### ISSUE THREAD

**Issue by muja** [flomotlik/formica#89]
`formica (deploy|new --deploy) --remove-on-error`

**Comment by flomotlik** [comment]
Thanks for sending this in, I really want every action taken on the stack to be a separate command though. While the flag is a nice convenience and probably fine on a new stack, it still makes something happen without me consciously triggering it after I see the error, which I don't really want Formica to do. It is relatively easy to just do `formica new -c configfile.yaml || formica remove -c configfile.yaml` if you want to remove it after it fails.
