### ISSUE TITLE
Add option to skip rollback on failed create.

### ISSUE THREAD

**Issue by muja** [flomotlik/formica#90]
Some resources will have some errors which can only be checked from inside the resouce. A specific case is Elastic Beanstalk: when your application fails to start, the environment will still emit a `CREATE_COMPLETE`, however, referencing the `Environment.EndpointURL` attribute, will cause the referencer to `CREATE_FAILED`. However, there is no way to tell what went wrong with the ElasticBeanstalk environment as the rollback process will destroy it.

The only way I could work around this was to disable every referencing resource and deploy. Once it (eventually) succeeds, i reenabled the resources and deployed those.

However, I don't know if it's technically possible to not rollback on failure -- ignore this if not.

**Comment by flomotlik** [comment]
>However, there is no way to tell what went wrong with the ElasticBeanstalk environment as the rollback process will destroy it.

Yup run into this as well, I typically use awsinfo (another tool I've built) to follow the Elasticbeanstalk events while the deployment happens in case there might be an issue. Another option is simply deploying a very simple version first and then updating it so its definitely there. Not a good option though.

> However, I don't know if it's technically possible to not rollback on failure -- ignore this if not

Yup that feature would definitely be helpful, don't think that exists though (at least I've never seen that option somewhere and I would understand why they wouldn't want that to be a feature either)

**Comment by muja** [comment]
Hi, just saw this by coincidence:

`aws cloudformation describe-stacks` shows a field `"DisableRollback": false` for my stacks, so maybe this is possible after all?

**Comment by muja** [comment]
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html

You can also pass a `--disable-rollback` flag to the `create-stack` command.

**Comment by flomotlik** [comment]
I don't think thats available on `create-change-set` and `execute-change-set` (at least I couldn't find it in the boto or awscli docs)
